<template>
	<section class="journal">
		<h2 class="journal__header">Journal</h2>

		<div class="slideshow">
			<h3 class="slideshow__title">title: {{ journalData[index].title }}</h3>

			<h3 class="slideshow__title">
				location: {{ journalData[index].location }}
			</h3>

			<h3 class="slideshow__title">artist: {{ journalData[index].artist }}</h3>

			<img :src="imageLink" />
			<!-- Buttons for navigating between the slideshow images, generated by iterating through the journalData list from database.js -->
			<button
				class="slideshow__button"
				:class="journalIndex === index ? 'slideshow__button--active' : ''"
				@click="changeImage(journalIndex)"
				v-for="(journal, journalIndex) in journalData"
				:key="journal.title"
			>
				{{ index }}
			</button>
		</div>
		<p>{{ journalData[index].image }}</p>
	</section>
</template>

<script>
import data from '../../assets/database.js';
export default {
	data() {
		return {
			//index used to find information for the slideshow from journalData.
			index: 0,

			//gets the journal array containing the 3 journal objects from database.js
			journalData: data.journal,
		};
	},

	methods: {
		changeImage(index) {
			this.index = index;
		},
	},

	computed: {
		imageLink() {
			return '../../assets/images/' + this.journalData[this.index].image;
		},
	},
};
</script>

<style>
/* Placeholder style while developing */
.journal {
	border: 2px solid gray;
	padding: 2rem;
}

.slideshow__button {
	border-radius: 50%;
	width: 50px;
	height: 50px;
	background: black;
}

.slideshow__button + .slideshow__button {
	margin-left: 20px;
}

.slideshow__button--active {
	border: 1px solid black;
	background: white;
}
</style>
