<template>
	<section class="journal">
		<h2 class="journal__header">Journal</h2>

		<div class="slideshow">
			<!-- Click left and right of box to go previous - next -->
			<div class="slideshow__controls">
				<button
					@click="slideControls(testIndex)"
					class="test"
					v-for="testIndex in 2"
					:key="testIndex"
					:class="{
						slideshow__previous: testIndex === 1,
						slideshow__next: testIndex === 2,
					}"
				></button>
			</div>
			<div class="slideshow__titles-container">
				<h3 class="slideshow__titles">"{{ journalData[index].title }}"</h3>

				<h3 class="slideshow__titles">
					{{ journalData[index].location }}
				</h3>

				<h3 class="slideshow__titles">
					{{ journalData[index].artist }}
				</h3>
			</div>

			<figure class="slideshow__image-container">
				<img class="slideshow__image" :src="imageLink" />
			</figure>
			<!-- Buttons for navigating between the slideshow images, generated by iterating through the journalData list from database.js -->
			<div class="slideshow__buttons-container">
				<button
					v-for="(journal, journalIndex) in journalData"
					class="slideshow__buttons"
					:class="journalIndex === index ? 'slideshow__button--active' : ''"
					@click="changeImage(journalIndex)"
					:key="journal.title"
				></button>
			</div>
		</div>
	</section>
</template>

<script>
import data from '../../assets/database.js';
export default {
	data() {
		return {
			//index used to find information for the slideshow from journalData.
			index: 0,

			//gets the journal array containing the 3 journal objects from database.js
			journalData: data.journal,
		};
	},

	methods: {
		changeImage(index) {
			this.index = index;
		},

		slideControls(testIndex) {
			// if (this.index >= 3 - 1) {
			// 	this.index = 0;
			// } else {
			// 	this.index++;
			// }
			// console.log(event.target);
			// console.log(testIndex);

			testIndex === 1 ? --this.index : ++this.index;
			if (this.index >= 3) {
				this.index = 0;
			} else if (this.index < 0) {
				this.index = 2;
			}
		},
	},

	computed: {
		imageLink() {
			return '../../assets/images/' + this.journalData[this.index].image;
		},
	},
};
</script>

<style>
/* Placeholder style while developing */
.journal {
	margin: 0 auto;
	max-width: 1920px;
}
.journal__header {
	text-align: center;
	font-size: 1.875rem;
	margin-bottom: 2.5rem;
	margin-top: 6.25rem;
}
.slideshow {
	position: relative;
	height: auto;
	background: black;
}

.slideshow__controls {
	position: absolute;
	display: flex;
	top: 0;
	left: 0;
	z-index: 800;
	width: 100%;
	height: 100%;
	-webkit-tap-highlight-color: transparent; /* Removes blue highlight on click */
}

.slideshow__previous {
	width: 100%;
	height: 100%;
}

.slideshow__next {
	width: 100%;
	height: 100%;
}

.slideshow__titles {
	font-size: 1.5rem;
	color: white;
	opacity: 100%;
}

.slideshow__titles-container {
	position: absolute;
	height: 100%;
	width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	text-align: center;
	z-index: 100;
}

.slideshow__image {
	object-fit: contain;
	opacity: 80%;
}

.slideshow__buttons-container {
	position: absolute;
	bottom: 0;
	width: 100%;
	text-align: center;
}

.slideshow__buttons {
	position: relative;
	/* Always keep buttons on top with z-index */
	z-index: 900;
	border-radius: 50%;
	width: 24px;
	height: 24px;
	background: transparent;
	border: 2px solid white;
	margin-bottom: 0.8rem;
}

.slideshow__buttons + .slideshow__buttons {
	margin-left: 10px;
}

.slideshow__button--active {
	border: 2px solid white;
	background: white;
}

@media screen and (min-width: 500px) {
	.slideshow__titles {
		font-size: 2rem;
	}
}

@media screen and (min-width: 928px) {
	.slideshow__titles {
		font-size: var(--main-header-size);
	}

	.slideshow__buttons {
		margin-bottom: 1.875rem;
	}
}
</style>
