<template>
	<section class="journal">
		<h2 class="journal__header">Journal</h2>

		<!-- Mouse overs to hide and show titles when in desktop mode -->
		<div
			class="slideshow"
			@mouseover="hover = true"
			@mouseleave="hover = false"
		>
			<!-- Click left and right of box to go previous - next -->
			<div class="slideshow__controls">
				<button
					@click="slideControls(testIndex)"
					v-for="testIndex in 2"
					:key="testIndex"
					:class="{
						slideshow__previous: testIndex === 1,
						slideshow__next: testIndex === 2,
					}"
				></button>
			</div>

			<div
				class="slideshow__titles-container"
				:class="{ 'slideshow__titles-container--hide': !hover }"
			>
				<h3 class="slideshow__titles">
					"{{ journalData[journalIndex].title }}"
				</h3>

				<h3 class="slideshow__titles">
					{{ journalData[journalIndex].location }}
				</h3>

				<h3 class="slideshow__titles">
					{{ journalData[journalIndex].artist }}
				</h3>
			</div>

			<figure>
				<img class="slideshow__images" :src="imageLink" />
			</figure>

			<!-- Buttons for navigating between the slideshow images, generated by iterating through the journalData list from database.js -->
			<div class="slideshow__buttons-container">
				<button
					v-for="(journal, index) in journalData"
					class="slideshow__buttons"
					:class="index === journalIndex ? 'slideshow__button--active' : ''"
					@click="changeImage(index)"
					:key="journal.title"
				></button>
			</div>
		</div>
	</section>
</template>

<script>
import data from '../../assets/database.js';
export default {
	data() {
		return {
			//index used to find information for the slideshow from journalData.
			journalIndex: 0,

			//gets the journal array containing the 3 journal objects from database.js
			journalData: data.journal,
			hover: false,
		};
	},

	methods: {
		changeImage(index) {
			this.journalIndex = index;
		},

		slideControls(testIndex) {
			testIndex === 1 ? --this.journalIndex : ++this.journalIndex;
			if (this.journalIndex >= 3) {
				this.journalIndex = 0;
			} else if (this.journalIndex < 0) {
				this.journalIndex = 2;
			}
		},
	},

	computed: {
		imageLink() {
			return '../../assets/images/' + this.journalData[this.journalIndex].image;
		},
	},
};
</script>

<style>
.slideshow__buttons,
.slideshow__controls {
	-webkit-tap-highlight-color: transparent; /* Removes blue highlight on click */
}

.journal {
	margin: 0 auto;
	max-width: 1920px;
}

.journal__header {
	text-align: center;
	margin-bottom: 2.5rem;
	margin-top: 6.25rem;
	font-size: var(--body-font-size);
}

.slideshow {
	position: relative;
	height: auto;
}

.slideshow__controls {
	position: absolute;
	display: flex;
	top: 0;
	left: 0;
	z-index: 2;
	width: 100%;
	height: 100%;
}

.slideshow__previous {
	width: 100%;
	height: 100%;
}

.slideshow__next {
	width: 100%;
	height: 100%;
}

.slideshow__titles-container {
	position: absolute;
	height: 100%;
	width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	text-align: center;
	z-index: 1;
	background: rgba(0, 0, 0, 0.199);
}

.slideshow__titles {
	font-size: 1rem;
	color: white;
	opacity: 100%;
}

.slideshow__images {
	max-height: 1113px;
}

.slideshow__buttons-container {
	position: absolute;
	width: 100%;
	bottom: 0;
	/* HIGHER z INDEX THAN THIS REBECCA!!!!!!!!!!!!!!!!!! */
	z-index: 3;
	text-align: center;
	padding-top: 1rem;
}

.slideshow__buttons {
	position: relative;
	border-radius: 50%;
	width: 24px;
	height: 24px;
	border: 2px solid white;
	margin-bottom: 0.8rem;
}

.slideshow__buttons + .slideshow__buttons {
	margin-left: 10px;
}

.slideshow__button--active {
	border: 2px solid white;
	background: white;
}

@media screen and (min-width: 500px) {
	.slideshow {
		margin: 0;
	}
	.slideshow__titles {
		font-size: 2rem;
	}
}

@media screen and (min-width: 928px) {
	.slideshow {
		margin: 0 1rem;
	}

	.slideshow__titles-container--hide {
		display: none;
	}

	.slideshow__titles {
		font-size: var(--heading-font-size);
	}

	.slideshow__buttons {
		margin-bottom: 1.875rem;
	}
}
</style>
